// 保留字、关键字表
export const scannerMap = {
    keyword: [
        'var',
        'let',
        'const',
        'return',
        'await',
        'if',
        'else',
        'do',
        'while',
        'continue',
        'break',
        'switch',
        'case',
        'finally',
        'function',
        'this',
        'throw',
        'try',
        'catch',
        'typeof',
        'instanceof',
        'new',
        'void',
        'class',
        'extends',
        'debugger',
    ],
    // 标识符
    identifiers: [
        'String',
        'Number',
        'Symbol',
        'Array',
        'Date',
        'Boolean',
        'Object',
        'Math',
    ],
    // 运算符
    operator: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '+=',
        '-=',
        '*=',
        '/=',
        '!',
        '++',
        '--',
        '|',
        '&',
        '&&',
        '||',
        '~',
        '<<',
        '>>',
        '<',
        '>',
        '<=',
        '>=',
        '===',
        '!==',
    ],
    // 分隔符
    delimiters: [',', '(', ')', '[', ']', ';', '{', '}', '.', "'", '"', '=>'],
};

// 词类型表
export enum wordMap {
    KEYWORD = 'keyword',
    IDENTIFIER = 'identifier',
    OPERATOR = 'operator',
    DELIMITER = 'delimiter',
}
