// 保留字、关键字表
export const scannerMap = {
    keyword: [
        'continue',
        'do',
        'while',
        'instanceof',
        'typeof',
        'case',
        'switch',
        'break',
        'else',
        'if',
        'new',
        'var',
        'let',
        'const',
        'finally',
        'return',
        'void',
        'default',
        'throw',
        'delete',
        'in',
        'try',
        'catch',
        'function',
        'this',
        'with',
        'debugger',
        'class',
        'extends',
        'struct',
        'Symbol',
    ],
    operator: [
        ',',
        '(',
        ')',
        '[',
        ']',
        '=>',
        '.',
        '!',
        '++',
        '--',
        '&',
        '~',
        '%',
        '<<',
        '>>',
        '<',
        '>',
        '<=',
        '>=',
        '===',
        '!==',
        '+',
        '-',
        '*',
        '/',
        '&&',
        '||',
        '+=',
        '-=',
        '*=',
        '/=',
        ';',
        '{',
        '}',
        "'",
        '"',
    ],
    // 整型常数
    constant: [],
};

// 词类型表
export const wordMap = {
    keyword: 'keyword',
    operator: 'operator',
    constant: 'constant',
};
